[package]
name = "dylink"
version = "0.0.0"
authors = ["Jonathan Thomason"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
once_cell = "1.16"

[dependencies.dylink_macro]
path = "../dylink_macro"
default-features = false

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.42"
features = [
	"Win32_Foundation",
	"Win32_Graphics_OpenGL",
	"Win32_System_LibraryLoader",
]

[profile.release]
codegen-units = 1
debug = false
strip = true
lto = true
overflow-checks = false
incremental = false
opt-level = "z"