[package]
name = "dylink"
version = "0.4.0"
authors = ["Jonathan Thomason"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["ffi"]
description = "Run-time dynamic linking utilities."
repository = "https://github.com/Razordor/dylink.git"
publish = false

[workspace]
members = ["dylink_macro"]

[dependencies]
once_cell = "1.16"
dylink_macro = {path="./dylink_macro"}

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.48"
features = ["Win32_Foundation", "Win32_System_LibraryLoader"]
default-features=false

[target.'cfg(unix)'.dependencies.libc]
version = "0.2"
default-features = false
