[package]
name = "dylink"
version = "0.5.0"
authors = ["Jonathan Thomason"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["ffi"]
description = "Run-time dynamic linking loader utilities"
repository = "https://github.com/Razordor/dylink.git"
publish = false

[workspace]
members = ["dylink_macro"]

[dependencies]
once_cell = "1.16"

[dependencies.dylink_macro]
version = "0.6"
path="./dylink_macro"
features = []
