[package]
name = "dylink"
version = "0.7.0"
edition = "2021"
authors = ["Jonathan Thomason"]
license = "MIT OR Apache-2.0"
keywords = ["ffi", "dlopen", "load", "shared", "lazy"]
categories = ["api-bindings"]
description = "Run-time dynamic linking loader utilities"
repository = "https://github.com/Razordor/dylink.git"
publish = true

[workspace]
members = ["dylink_macro"]

[dependencies.dylink_macro]
version = "0.8"
path="./dylink_macro"

[dependencies]
once_cell = "1.17"