[package]
name = "dylink"
version = "0.1.0"
authors = ["Jonathan Thomason"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["external-ffi-bindings"]
publish = false

[dependencies]
once_cell = "1.16"

[dependencies.dylink_macro]
git = "https://github.com/Razordor/dylink_macro"
#path = "../dylink_macro"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.45"
features = ["Win32_Foundation", "Win32_System_LibraryLoader"]

[target.'cfg(unix)'.dependencies.libc]
version = "0.2"
