[package]
name = "dylink"
version = "0.0.0"
authors = ["Jonathan Thomason"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
once_cell = "1.10.0"
dylink_macro = "0.1.0"

[target.'cfg(windows)'.dependencies.windows]
version = "0.36"
features = [
	"Win32_Foundation",
	"Win32_Graphics_OpenGL",	
]