[package]
name = "dylink"
version = "0.0.0"
authors = ["Jonathan Thomason"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["external-ffi-bindings"]
publish = false

[dependencies]
once_cell = "1.16"

libc = "0.2"

[dependencies.dylink_macro]
path = "../dylink_macro"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.42"
features = [
	"Win32_Foundation",
	"Win32_Graphics_OpenGL",
	"Win32_System_LibraryLoader",
]

#[target.'cfg(not(windows))'.dependencies.libc]
#version = "0.2"

[features]
opaque_types = []