[package]
name = "dylink"
version = "0.2.2"
authors = ["Jonathan Thomason"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["ffi"]
description = "Dynamic function loading utilities."
repository = "https://github.com/Razordor/dylink.git"
#publish = false

[dependencies]
once_cell = "1.16"
dylink_macro = "0.4"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.48"
features = ["Win32_Foundation", "Win32_System_LibraryLoader"]

[target.'cfg(unix)'.dependencies.libc]
version = "0.2"
