name: dylink-rs

on:
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose --all
    - name: Run tests
      run: cargo test --verbose -- --skip test_vk_instance_layer_properties
  
  test-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose --all
    - name: Run tests
      # Skipping vulkan test because drivers are not gaurenteed on the system, especially on GitHub's VM.
      # Skipping lifetimes test since actions doesn't know how pointers work for some reason?
      run: cargo test --verbose -- --skip test_vk_instance_layer_properties --skip test_win32_lifetimes
      
  test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose --all
    # There are currently no tests for macos